### ISSUE TITLE
BUG: DevExpress.Data.UnboundColumnDataTypeValidator+InvalidTypeException

### ISSUE THREAD

**Issue by lars18th** [PredatH0r/ChanSort#408]
Hi @PredatH0r ,

This error raises when horizontal scrolling with a M3U file opened:
```
---------------------------
Fehler bei Programmausführung
---------------------------
Bei der Programmausführung trat folgender Fehler auf:
DevExpress.Data.UnboundColumnDataTypeValidator+InvalidTypeException: Incorrect value assigned to the +FreqInMhz column, row 0. Value type: System.Decimal, expected value type: System.String.
The DevExpress.Data.UnboundColumnDataTypeValidator.AllowInvalidTypes option allows you to disable the exception, but it does not resolve the underlying issue.
   at DevExpress.Data.UnboundColumnDataTypeValidator.Throw(Type valueType, Type expectedType, String propertyName, Int32 rowIndex)
   at DevExpress.Data.UnboundColumnDataEventArgs.set_Value(Object value)
   at ChanSort.Ui.MainForm.gview_CustomUnboundColumnData(Object sender, CustomColumnDataEventArgs e)
   at DevExpress.XtraGrid.Views.Base.ColumnView.RaiseCustomUnboundColumnData(CustomColumnDataEventArgs e)
   at DevExpress.XtraGrid.Views.Base.ColumnView.GetUnboundDataCore(Int32 listSourceRow1, DataColumnInfo column, Object value)
   at DevExpress.XtraGrid.Views.Grid.GridView.GetRowCellValue(Int32 rowHandle, GridColumn column, OperationCompleted completed)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CalcRowCellDrawInfoCore(GridDataRowInfo ri, GridColumnInfoArgs ci, GridCellInfo cell, GridColumnInfoArgs nextColumn, Boolean calcEditInfo, GridRow nextRow, Boolean allowCache, Rectangle cellBounds)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CalcRowCellDrawInfo(GridDataRowInfo ri, GridColumnInfoArgs ci, GridCellInfo cell, GridColumnInfoArgs nextColumn, Boolean calcEditInfo, GridRow nextRow)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CalcRowCellsDrawInfo(GridDataRowInfo ri, GridColumnsInfo columnsInfo, GridRow nextRow)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CalcDataRow(GridDataRowInfo ri, GridRow row, GridRow nextRow)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CalcRowsDrawInfo()
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CalcGridInfo()
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CalcAfterHorzScroll(Graphics g, Rectangle bounds)
   at DevExpress.XtraGrid.Views.Grid.GridView.DoLeftCoordChanged(Boolean allowPartialScroll)
   at DevExpress.XtraGrid.Views.Grid.GridView.set_LeftCoord(Int32 value)
   at DevExpress.XtraGrid.Views.Grid.GridView.OnHScroll(Object sender, EventArgs e)
   at DevExpress.XtraEditors.ScrollBarBase.OnValueChangedCore(EventArgs e)
   at DevExpress.XtraEditors.ScrollTouchBase.OnValueChanged(EventArgs e)
   at DevExpress.XtraEditors.ScrollBarBase.set_Value(Int32 value)
   at DevExpress.XtraEditors.ScrollBarBase.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraControl.WndProc(Message& m)
   at DevExpress.XtraEditors.ScrollBarBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
OK
---------------------------
```

The playlist is a custom SAT>IP M3U file moddified that instead of the regular SAT>IP URL it contains a proxy. Example:
```
#EXTM3U
#
#EXTINF:-1 tvg-id="KiKa GER HD" tvg-logo="http://proxy-server.local/kika.png" , KiKA HD
#EXTALBUMARTURL:http://proxy-server.local/kika.png
http://proxy-server.local/channel-kika
```

I hope you want to fix it.
Thank you.

**Comment by PredatH0r** [comment]
fixed in 2024-08-18 (or earlier)
